#!/usr/bin/env python

import bottle

application = bottle.Bottle()

@application.route('/')
@application.route('/hello/')
@application.route('/hello/<name>')
def greet(name='Stranger'):
    return bottle.template('Hello {{name}}, how are you?', name=name)
