#!/usr/bin/env python

import os, pymongo
from bottle import template, Bottle, route

application = Bottle()

@route('/')
@application.route('/hello')
@route('/hello/<name>')
def greet(name='Stranger'):
    return template('Hello {{name}}, how are you?', name=name)

"""
@application.route("/ws/parks")
def parks():
    conn = pymongo.Connnection(os.environ['OPENSHIFT_MONGODB_URL'])
    db = conn.parks
    result = db.parkpoints.find()
    return str(json.dumps({'results':list(result)}, default=json_util.default))



"""
