#!/usr/bin/env python

import os, pymongo
from bottle import template, Bottle, route

application = Bottle()

@route('/')
@route('/hello')
@route('/hello/<name>')
def greet(name='Stranger'):
    return template('Hello {{name}}, how are you?', name=name)

"""
@application.route("/ws/parks")
def parks():
    conn = pymongo.Connnection(
